apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka
  interval: 10m0s
  path: ./infra/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
