apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: platform-system
  labels:
    strimzi.io/cluster: kafka-dev
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 1Gi
